services:
  db:
    image: mariadb:10.11
    container_name: mediawiki-db
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

  mediawiki:
    image: mediawiki:1.44
    container_name: mediawiki
    restart: unless-stopped
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - ./images:/var/html/images
      - ./extensions:/var/www/html/extensions
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
      - ./captcha.php:/var/www/html/captcha.php
    depends_on:
      - db

volumes:
  db_data: